In [1]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as pt
% matplotlib inline

In [8]:
def ChebyshevGrid1D(n):
    assert(n>0)
    nodes = []
    for j in range(0,n+1):
        nodes.append(np.cos(j*np.pi/n));
    return np.array(nodes)

In [9]:
def FirstOrderDifferentiationMatrix(n):
    M = np.zeros((n+1, n+1));
    for i in range(0, n+1):
        xi = np.cos(i*np.pi/n)
        for j in range(0, n+1):
            xj = np.cos(j*np.pi/n)
            if (i==0 and j==0):
                entry = (2*(n**2) + 1)/6.0;
            elif (i==n and j==n):
                entry = -(2*(n**2) + 1)/6.0;
            elif (i==j):
                entry = -xj / (2*( 1-(xj**2) ));
            else:
                ci = (2.0 if(i==0 or i==n) else 1.0);
                cj = (2.0 if(j==0 or j==n) else 1.0);
                entry = (ci/cj) * ( ( (-1)**(i+j) )/(xi - xj) );
            M[i, j] = entry;
    return M

In [10]:
def SecondOrderDifferentiationMatrix(n):
    M = np.zeros((n+1, n+1));
    for i in range(0, n+1):
        xi = np.cos(i*np.pi/n)
        for j in range(0, n+1):
            xj = np.cos(j*np.pi/n)
            # First fill-in values at the boundaries
            if ( (i==0 and j==0) or (i==n and j==n) ):
                entry = ((n**4) - 1)/15.0
            # Then fill-in values at the first row
            elif (i==0):
                cj = (2.0 if(j==0 or j==n) else 1.0);
                c = ( (-1)**(j) ) / cj 
                num = ( 2*(n**2) + 1 )*(1-xj) - 6
                den = (1 - xj)**2
                entry = (2/3.0)*c*(num / den)
            # Then fill-in values at the last row
            elif (i == n):
                cj = (2.0 if(j==0 or j==n) else 1.0);
                c = ( (-1)**(j+n) ) / cj 
                num = ( 2*(n**2) + 1 )*(1+xj) - 6
                den = (1 + xj)**2
                entry = (2/3.0)*c*(num / den)
            # Then fill-in values at the diagonal
            elif (i==j):
                num = ((n**2)-1)*(1-(xi**2)) + 3
                den = 3*( (1-(xi**2))**2 )
                entry = - num/den;
            # At last, fill-in the rest of the values.
            else:
                cj = (2.0 if(j==0 or j==n) else 1.0);
                c = ( (-1)**(i+j) ) / cj 
                num = (xi**2) + (xi*xj) - 2
                den = ( 1-(xi**2) )*( (xi-xj)**2 )
                entry = c*(num / den)
            M[i, j] = entry;
    return M

In [11]:
mesh = ChebyshevGrid1D(3)
D1 = FirstOrderDifferentiationMatrix(3)
D2 = SecondOrderDifferentiationMatrix(3)
print(mesh)
print(D1)
print(D2)

[ 1.   0.5 -0.5 -1. ]
[[ 3.16666667 -4.          1.33333333 -0.5       ]
 [ 1.         -0.33333333 -1.          0.33333333]
 [-0.33333333  1.          0.33333333 -1.        ]
 [ 0.5        -1.33333333  4.         -3.16666667]]
[[ 5.33333333 -9.33333333  6.66666667 -2.66666667]
 [ 3.33333333 -5.33333333  2.66666667 -0.66666667]
 [-0.66666667  2.66666667 -5.33333333  3.33333333]
 [-2.66666667  6.66666667 -9.33333333  5.33333333]]


In [105]:
def f1(x):
    return np.exp(x)

def f2(x):
	return np.exp(x)*np.sin(5*x);

In [106]:
def df1(x):
    return np.exp(x)

def df2(x):
	return 2*np.exp(x)*( 5*np.cos(5*x) - 12*np.sin(5*x) );

In [107]:
f = f1
true_sol = df1

In [108]:
n = 40

In [109]:
mesh = ChebyshevGrid1D(n)

In [110]:
diff_mat = SecondOrderDifferentiationMatrix(n)

In [111]:
us = f(mesh)

In [112]:
u_approx = diff_mat.dot(us)

In [113]:
la.norm(true_sol(mesh)-u_approx, np.inf)

2.1846706665940019e-09